### ISSUE TITLE
Data Prep Issues

### ISSUE THREAD

**Issue by DCrouse** [tesera/pygypsy#57]
- the option syntax needs to be re-written on the help menu.  doesn't work with the commas as shown.
command needs to be something like this, gypsy prep -i id_l1 one_thousand.csv
- when using the -n option on the test dataset, where the numbers are all integer in the id_l1 field, I get an error message indicating the id_l1 field is not a valid integer field.  However, this works when using the -i option, so gypsy is assuming the id_field is a text string when there really is not a character in the field.  I think this is related to csv and what the imported field settings are ... but the ids really are integer in nature and probably should be treated as such or just remove the -n option ... we just need to know what the stand-id is regardless of numeric or string. 
- the id_l1 fieldname is not transferred to the output dataset when using any or none of the options ... the data is transferred but not the fieldname in the header.
- when I run the option to direct output to another folder, the prep runs through but does not export a file to the folder ... not sure where it goes

**Comment by jo-tham** [comment]
I think point 3 needs to be addressed and the other ones are from old gypsy. More details below; please confirm

- hey @DCrouse can you clarify about the commas in first point?

if you mean the commas in the lines below, they are only there to indicate that `-c` **or** `--config` can be used

```
  -c, --config-file PATH
  -h, --help              Show this message and exit.
```

it is convention, with command usage, that the option and its value are separated by ` ` (empty space) or `=` and i think either of those work with pygypsy

-----------------

- Ya i think you are using the old gypsy; -n and -i  options aren't present in pygypsy


----------------------------

- good catch; i will update it so that the index field always maintains its column name in other output


-------------------------

- i think this one is also a relict of old gypsy
