### ISSUE TITLE
hard to read colours in console

### ISSUE THREAD

**Issue by DCrouse** [tesera/pygypsy#63]
It's hard to read the blue coloured text in the console ...  can that be changed?

![image](https://cloud.githubusercontent.com/assets/1724094/21274602/4fe74876-c386-11e6-801a-8e7a6c949661.png)

**Comment by jo-tham** [comment]
it can be changed @DCrouse. at this point the focus is on functionality/bugs & docs so its low priority. it should only take a few minutes, though, so i'll try to adjust it quickly.

**Comment by jo-tham** [comment]
@DCrouse want to get your take here

the color log is used so that errors and warnings will be emphasized; i've always found it very helpful to see potential problems prefixed in yellow/read

on my display the blue works well on black and white backgrounds (see attached image; though if your display is not very good the attached image might not help :P )

i wonder if your display settings are causing it to be harder to read (resolution/contrast/saturation)

there's probably no color i can change it to that will work any better on white and black backgrounds and i don't want to assume one background color or the other.

so, I think the options are

- change blue to something else (not gonna do that, will end up in same scenario or spending lots of time tuning AFAICT)

- play with your display settings and see if it improves at all

- change to standard terminal text color, which the terminal determines the color of (it will be black on white backgrounds and vice versa) but then we lose the colored emphasis for messages indicative of problems
  - users can grep/find for error and warning lines

i'm leaning towards the last option but wonder if you're interested in color if adjusting your display makes it more readable.

<img width="814" alt="screen shot 2016-12-16 at 1 03 51 pm" src="https://cloud.githubusercontent.com/assets/7353689/21278582/ec01257e-c390-11e6-8368-7963ea7b5e3a.png">

**Comment by DCrouse** [comment]
yeah, your blues on your screen are soo much better - I can read yours.  I'll look into the display settings

**Comment by jo-tham** [comment]
closing this @DCrouse please reopen if you can't find suitable display settings
