### ISSUE TITLE
User Documentation

### ISSUE THREAD

**Issue by CarolCrouse** [tesera/pygypsy#77]
docs site user guide is incomplete

http://pygypsy.readthedocs.io/en/latest/#user-guide

**Comment by CarolCrouse** [comment]
For the data prep section you've written the command: 
pygypsy prep --config-file ./pygypsy-output/config.json /path/to/your/plot-data.csv

In order to get it to run I had to change it to:
pygypsy prep --config-file .\pygypsy-output\pygypsy-config.json D:\Gypsy_testing_011717\One_Thousand.csv

I changed the / to \ this may be a windows vs apple issue?
I changed config.json to pygypsy-config.json because this is the config file name made during the config file setup.

**Comment by jo-tham** [comment]
I changed the / to \ this may be a windows vs apple issue?

Yep; i could add a note to the docs use the 'path separator for your operating system'... The only trouble is, we kind of have to do it everywhere there's paths in the documentation for that to really be effective, and that would quickly become burdensome. So since it doesn't take long to figure out I'd rather leave it to users to learn.

    I changed config.json to pygypsy-config.json because this is the config file name made during the config file setup.

That's the right thing to do; the config.json is just an example. I will change it to make it clearer

**Comment by CarolCrouse** [comment]
After the prep process you state "Take note of the consolte output to see where the prepared plot data is created."
But the console did not give a location for the prepped csv file

**Comment by CarolCrouse** [comment]
Under the running simulation section the output prepped file should change from /pygypsy-output/plot-data-prepped.csv to /pygypsy-output/plot_data_prepped.csv.   - to _

Also can the Data Management section be moved to the beginning.  Reading the directions as a sequence of steps I found out at the end how to set up the outputs to go to a user defined directory when I would want to set that up at the beginning.

**Comment by jo-tham** [comment]
thx @CarolCrouse - i added this to the code.

it will be available in the next release, since it's a very minor change i won't do the release now. the output of the prep command does end up under the directory specified by `--output-dir` (pygypsy-output by default) with filename `plot_tabe_prepped.csv`.

i also revised the docs to move data management to the beginning

**Comment by jo-tham** [comment]
Under the running simulation section the output prepped file should change from /pygypsy-output/plot-data-prepped.csv to /pygypsy-output/plot_data_prepped.csv. - to _

done :)

**Comment by jo-tham** [comment]
i'm going to merge the #78 and close this issue
