### ISSUE TITLE
some tree age estimates do not converge

### ISSUE THREAD

**Issue by CarolCrouse** [tesera/pygypsy#79]
It ran through the 1000 data set fine and is processing through the 10,000.  There is still a warning that comes up for stands >1000 yr old. 

Jotham let me know if you want the outputs for review.

![image](https://cloud.githubusercontent.com/assets/7502509/22045086/7c7e47dc-dcd5-11e6-9f5b-160ca873eddd.png)

**Comment by jo-tham** [comment]
thx @CarolCrouse 

this is the domain of @ianmoss maybe @juliannosambatti - do we need to be able to configure the tolerances for the tree age estimation? or can we ignore these warnings?

if we can ignore them, the action should be to use the file log handler for these messages. it's low priority

i can advise on how to implement some changes here, but lets wait to hear from them as the desired outcome to do

**Comment by ianmoss** [comment]
Why are we computing tree age using GYPSY.  This is not appropriate. We should be computing site index given height and age.

**Comment by ianmoss** [comment]
... and tree species.

**Comment by jo-tham** [comment]
@juliannosambatti can you field ians question above?

**Comment by juliannosambatti** [comment]
Actually I am with Ian. 

The only time I can possibly see tree age being estimated is when we get the initial data is given where only the leading species age is provided, then there is a routine that iteratively assign ages and SI together. After that, age is just the dependent variable. Is this where we are getting the problem?

**Comment by jo-tham** [comment]
@juliannosambatti can you verify by checking the implementation and posting the links to the corresponding lines here? e.g. 

https://github.com/tesera/pygypsy/blob/dev/pygypsy/forward_simulation.py#L37

**Comment by juliannosambatti** [comment]
Ian and I are discussing the issue. It seems there is a particular combination of numbers that makes the Pl too old because its estimated height is too large with respect to SI, meaning that the tree has grown for quite a long time since 50 years of age. Since pine does not grow fast, age goes to the roof. We are thinking in alternatives to circumvent that.

**Comment by juliannosambatti** [comment]
Alternative to solve:
if Ages is too high, stop and:
1 - define Age as a maximum age for each group: Aw: 200; Pl: 250; SW and Sb: 450
2 - use this age and height to recalculate SI

**Comment by ianmoss** [comment]
Note that this is a conservative solution to this issue.  It is by no means the only solution.  It should be included as part of any documentation as to how this variant of the model works.

**Comment by jo-tham** [comment]
talked with julianno about the implementation of this, and a few things come to mind

# define Age as a maximum age...

for each group: Aw: 200; Pl: 250; SW and Sb: 450

makes sense, lets do this. here's an outline of steps for @juliannosambatti

0. create a branch called #79/tree-age-estimation-convergence

1. add test(s) for the `computeTreeAge` function that uses parameters which are known not to converge. assert that the value returned is the maximum value for the species
    - create a new file under `tests/` called `test_compute_tree_age.py`
    - create a test function, test_compute_tree_age, and parametrize it to test all species - see [here](http://doc.pytest.org/en/latest/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions) for parametrization help
    - create a test function, test_compute_nonconvergent_tree_age, and parametrize it to make sure nonconvergent parameters for each species yield the maximum age
 
2. revise the `computeTreeAge` function below [this line.](https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L268) to return the maximum age for the species if it does not converge 

3. while in the `asaCompileAgeGivenSpSiHt` module, update the print statements to use the logger. log at the warning level, [as is done for other nonconvergence log messages](https://github.com/tesera/pygypsy/blob/dev/pygypsy/basal_area_factor.py#L97). 
    - Added points if you resolve the linting errors in this file

4. open pull request

5. review & merge 

6. should make a release here so that @CarolCrouse can continue testing with larger datasets. @juliannosambatti can try this using the [documentation](http://pygypsy.readthedocs.io/en/latest/contributing.html#release-process)

# use this age and height to recalculate SI

This is difficult to endorse right away on a couple levels. 

There is a circular dependency here, the age estimation uses the originally estimate site index, so if we set age to the max age, and estimate a new site index, should we estimate the age again using the new site index? 

In addition, to following this path, as we have done so far, is a risk to further development and maintenance so we should only do it if we absolutely have to. See last section for alternative

To move ahead, I suggest going through the following steps:

0. discuss the what distribution of difference in site index from the dominant species site index vs the [ComputeGypsySiteIndex function](https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L3) are acceptable or unacceptable in a scientific context and in an operational/business context
1. demonstrate whether it is warranted to update the site index by comparing the site index estimated from the dominant species site index against the site index estimated using the [ComputeGypsySiteIndex](https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L3) function. 
    1. with the revised code (so that the maximum age is returned for nonconvergent age estimation) run data prep on a sample of plots which are known to have a convergence problem (work with @CarolCrouse to get these plots from her sample data). see the [docs](http://pygypsy.readthedocs.io/en/latest/usage.html) for help with the CLI. the output of data prep will include the site index estimated from dominant species, and other parameters
    2. in a script, or better yet an ipython notebook, read in the file output by data prep, and use the [ComputeGypsySiteIndex function](https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L3) to calculate the site index using the maximum age and other properties
    3. make some statistical summaries of the differences between the:
        - site index as estimated using the dominant species site index relationships
        - the site index as estimated using the topheight, bhage, and total age from the prepped data
2. given the differences demonstrated at the end of 1, decide to update the site index or not
3. if not, process is **done**. if site index is to be recalculated:

hack it in right away
-----------------------------
After the age computation is done we have to check if the age is equal to the max age *and* that this was from nonconvergence. If so, recalculate site index using [this](https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L3) function

- how can we test for this?
- use a function, given the species dict, should check the ages and update the site index if the age is the maximum age; this is a testable unit

refactor
-------------------------------
there is an emerging design. this state management, repetition of everything for 4 species, and sphagetti code) is an symptom of our current design issue: we are tracking a lot of state and species specific behaviour which would better belong on a class. 

specifically, the change in species height is a state change in what could be a class property (plot.lodgepole_pine.height). 

the property's public setter could have a callback, so that when the property is changed it automatically triggers a recalculation of a dependent property (plot.lodgepole_pine.site_index) which sets the value with a private setter that doesn't trigger this recalculation.

this requires a more thorough design, review, and implementation but moves the code more towards asset from liability. wide discussion to have here with @alxjalxj

**Comment by jo-tham** [comment]
@juliannosambatti @ianmoss @alxjalxj process for this outlined above. some significant things to consider. @juliannosambatti i can pair with you when you get stuck

**Comment by juliannosambatti** [comment]
This is a file that compares the Site Index estimates for Age>1000 and Age = 200 for species Aw and Age = 250 for species Pl, which were the tow problematic ones (last 4 columns of the table). These plots were filtered out of 10000 plots, following the idea that, in these cases when Age>1000, we could set a top maximum age based on what it is known for each species and use that Age to recalculate Site index (also using Height from the previous run). It turns out that, when we reduce the Age from >1000 to 200 or 250 without changing other parameters, Site Index estimates invariably increase from 5-15%. To me this makes sense because, by doing so, we are forcing the trees to grow faster, i.e,. reach the same height 750 or 800 years earlier, depending on the species. As a result, Site Index must be higher as well. 

In general, using the SI with Ages>1000 is more conservative in that, site productivity will be lower. In addition the differences between these estimates are in the order of 5-15%, making it questionable whether it is worthwhile changing the code because of that. 



[plot_table_testSI.xlsx](https://github.com/tesera/pygypsy/files/719888/plot_table_testSI.xlsx)

**Comment by jo-tham** [comment]
@juliannosambatti please upload in csv
xlsx is not a very portable format

**Comment by juliannosambatti** [comment]
[plot_table_testSI.csv.zip](https://github.com/tesera/pygypsy/files/720007/plot_table_testSI.csv.zip)

**Comment by jo-tham** [comment]
thanks 

also @juliannosambatti excellent summary; thanks for looking into this!

I want to highlight that the scenario in the scenario with age > 1000, the site index is calculated a completely different way than when we limit it to the heuristic maximum age for each species.

- when the age is estimated at > 1000, the site index has already been estimated using this relationships between dominant species site index with these functions:
    - https://github.com/tesera/pygypsy/blob/dev/pygypsy/site_index.py#L42

- after the age is estimated, julianno was re estimated  site index using this function
    - https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L3

**another candidate comparison would be to use the function linked directly above to estimate the site index using the estimated age (i.e. the age > 1000).**

I hope that makes sense 

**Is the dominant species site index measured in the field or estimated from other measurements?** Do we know the accuracy in the estimators using the [dominant species site index](https://github.com/tesera/pygypsy/blob/dev/pygypsy/site_index.py#L42) and the secondary species site indices, or in the [function to estimate site index given the species specific properties](https://github.com/tesera/pygypsy/blob/dev/pygypsy/asaCompileAgeGivenSpSiHt.py#L3)

cc @ianmoss

**Comment by juliannosambatti** [comment]
Ian and I spoke and worked with the problem we found that was freezing the processing (treeHt <=1.3). Also, we decided to update the Ages to maximum ages (e.g., maxageAw=200) and SI calculated from maxage. This should be the starting point for the inventory update.

**Comment by juliannosambatti** [comment]
when the ratio between totalHeight / startHt decreases, it will, at some point show problems. For example
startHt = 0.01 and totalHeight = 0.99 works
startHt = 0.01 and totalHeight = 0.90 doesn't work

raising startHt with respect to totalHeight will have the same effect

cc @ianmoss

**Comment by jo-tham** [comment]
OK @juliannosambatti; i suggest we merge your branch and do a release ASAP so that @CarolCrouse can continue testing with the larger dataset (without updating the SI - we can learn more from that concurrently while you implement the SI update)

Once we merge that, please start the SI update on a new branch. 

For updating the SI, recall https://github.com/tesera/pygypsy/issues/79#issuecomment-273591962

Sounds like for the sake of time we will hack this change in without refactoring. If you have an idea in mind for how to implement, please post it here. Or we can video chat and dig into it.

**Comment by juliannosambatti** [comment]
One issue I forgot to mention here. The reason one particular plot crashed the program was not so much that it had height = 1.3 (which is the breast height age = 0), but this plot showed Site Index = 0. It looks like the plot data may not be correct. Is it possible to verify the reason for that SI=0?

cc @CarolCrouse @jo-tham

**Comment by CarolCrouse** [comment]
@juliannosambatti I checked the plot data and there is a single plot where the SI = 0.  Not sure why but perhaps it's a typo.  Not sure how we can deal with issues like that where there are typos in the data.

**Comment by juliannosambatti** [comment]
Yeap, that's the one that failed. We may need to prepare (if it is not already available), down the road, a script that tracks these things down. Negative numbers in some variables, SI=0 etc. We might want to start listing these to create the script.

**Comment by jo-tham** [comment]
> I checked the plot data and there is a single plot where the SI = 0. Not sure why but perhaps it's a typo. Not sure how we can deal with issues like that where there are typos in the data.

@CarolCrouse @juliannosambatti #76 would fix this and other potential issues for the time being

down the line we add a better interface for data validation as @juliannosambatti suggests.

**Comment by juliannosambatti** [comment]
The main problem now is that, when plots are too young, bhage gets to be negative and this is plugged in some functions having log(negative bhage), making the program to crash. One alternative discusses by Ian and Julianno is to bring the bhage to 0 and updating the height while keeping other variables constant. and then running Gypsy.
